name: Gemini Hello World

on:
  workflow_dispatch:

jobs:
  run-gemini:
    runs-on: ubuntu-latest
    steps:
      - name: Run Prompt
        uses: google-github-actions/run-gemini-cli@2a77eb258d8d2447292fd5d9df6e7b49533d4f37
        id: analyze-ci-error
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            Use `actions/github-script@v7` to implement a GitHub Action step to print a hello world.
